FROM node:alpine

WORKDIR /app

RUN apk update
RUN apk add python3 make g++

ADD ./ /app/

ENV NODE_OPTIONS=--openssl-legacy-provider
ENV API_URL=http://localhost:5000
ENV DOMAIN=localhost
ENV HOST=0.0.0.0

RUN yarn install
RUN yarn build

CMD ["yarn", "start"]
