version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    working_dir: '/app'
    volumes:
      - './:/app'
      - node_modules_volume:/app/node_modules
    tty: true
    env_file:
      - './.env'
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
